### ISSUE TITLE
Drone Tests

### ISSUE THREAD

**Issue by junn-hope** [nakujaproject/recoveryN3#32]

**Comment by junn-hope** [comment]
Prepare for Drone test set for 16th March

**Comment by bytecod3** [comment]
Drone tests were carried out on 23rdMarch 2023. The test was a failure because as the team experienced power supply issue during the day. The power supplying the ESP32 was not regulated so the ESP kept on overheating. We have rescheduled the drone test for another day in a weeks time.

**Comment by junn-hope** [comment]
Shouldn't we maintain this issue as **In Progress** until we successfully perform our tests?
